# Wk2 Trk3, Day 1
<br>

# Exercises: NumPy
---
<br>

#### CSAA2022

Welcome to the first half of today's lab! In this lab, we are going to practice the fundamentals of numpy by creating arrays, accessing elements, subsetting using Boolean indexing and finally, we are also going to practice some well known numpy functions. 


Of course, we are not able to cover it all and as such we recommend the online resouces below. As always, documentation is your friend, so make sure you have a look if uncertain. 

Useful references: 
* [Official NumPy reference ](https://numpy.org/doc/stable/reference/index.html)
* [Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)


In [1]:
#first step if we want to use functions that have been already implemented in a library is to import that library

#traditional way of importing numpy
import numpy as np

#### Task 1: Mastering the basics

##### Part A: Create some arrays


* Create an array from the following list 
        sample_list = [1.0,4.0,9.0,23.0]

* **Do not use** *np.array* for the next problems: 
    * create a 10 x 10 matrix of all ones
    * a 15 element vector, with all elements equal to np.pi
    * an 1D array with elements between 0 and 50, stepping by 2
    * an array of random numbers of 0 mean and unit std; choose the size yourselves 
    * create an array of even numbers between 100 and 500 and then divide it by 2





In [5]:
matrix_1 = np.ones((10,10), dtype=int)

In [6]:
matrix_1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
pi_ = np.full((15), np.pi)
pi_

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [44]:
# an 1D array with elements between 0 and 50, stepping by 2
one_d = np.arange(0, 50, 2)
one_d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [45]:
# an array of random numbers of 0 mean and unit std; choose the size yourselves
random_numbers = np.random.randn(4,5)
random_numbers

array([[ 0.39220412, -0.47762695,  0.47331774,  1.69140022, -0.57057201],
       [ 1.12293504, -1.57591732,  0.68556898,  0.09124149, -0.60237266],
       [-1.10300214, -0.14476676, -0.35098944,  0.61556337,  0.28929372],
       [-0.68313017,  0.22380647, -0.99048252, -0.96561917, -0.29369189]])

In [46]:
# create an array of even numbers between 100 and 500 and then divide it by 2
even_numbers = np.arange(100, 500, 2) / 2
even_numbers

array([ 50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
        61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
        72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,
        83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,
        94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102., 103., 104.,
       105., 106., 107., 108., 109., 110., 111., 112., 113., 114., 115.,
       116., 117., 118., 119., 120., 121., 122., 123., 124., 125., 126.,
       127., 128., 129., 130., 131., 132., 133., 134., 135., 136., 137.,
       138., 139., 140., 141., 142., 143., 144., 145., 146., 147., 148.,
       149., 150., 151., 152., 153., 154., 155., 156., 157., 158., 159.,
       160., 161., 162., 163., 164., 165., 166., 167., 168., 169., 170.,
       171., 172., 173., 174., 175., 176., 177., 178., 179., 180., 181.,
       182., 183., 184., 185., 186., 187., 188., 189., 190., 191., 192.,
       193., 194., 195., 196., 197., 198., 199., 20

##### Part B: Practing indexing and slicing

Given the array below, access the following elements:

* access 39 using negative indexing
* slice the first five elements of each row
* slice the numbers between 0 and 5
* slice all the odd numbers (use Boolean indexing)

In [11]:
test1 = np.arange(0,40).reshape(2,20)
test1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [14]:
test1[1,-1]

39

In [48]:
# slice the first five elements of each row
first_five_elements = test1[:,0:5]
first_five_elements

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [51]:
# slice the numbers between 0 and 5
between_zero_five = test1[0,0:5]
between_zero_five

array([0, 1, 2, 3, 4])

In [49]:
# slice all the odd numbers (use Boolean indexing)
all_odd = test1[test1 %2 != 0]
all_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

#### Task 2: Snails

The snails data can be found in the dataLab folder. 

Groups of 20 snails were held for periods of 1, 2, 3 or 4 weeks in carefully controlled conditions of temperature
and relative humidity. The two species of snails are labelled as 0 and 1. At the end of the exposure time the snails were tested to see if
they had survived.

Data format, 6 columns as follows: 
    
    * species (0 or 1)
    * exposure (weeks)
    * humidity
    * temperature
    * ndeaths
    * nsnails (initial number at the start)
    
    
    
**What you need to do**: 

* Read the data. Use numpy!
* Practice indexing and slicing: 
        * temperature of last entry
        * humidity of the 5th entry
        * get 2nd and 3rd column
        * get the first 5 rows
        
* Compute the following: 
        * total number of deaths :(
        * total number of snails that survived :)
        * max temperature
        * mean humidity
        * average death rate 
* Split the snails in 2 arrays based on their species
* Which group of snails has the highest average death rate? 
* What are the optimum living conditions (temperature and humidity) for snails? Use only snails kept for the full duration of the experiment. 


In [15]:
file = np.loadtxt("labData/snails.txt")

In [21]:
#np.set_printoptions(suppress=True)

columns are * species (0 or 1) * exposure (weeks) * humidity * temperature * ndeaths * nsnails (initial number at the start)

In [19]:
file.shape

(96, 6)

In [24]:
# temperature of last entry
last_entry_temp = file[95,3]
last_entry_temp

20.0

In [26]:
# humidity of the 5th entry
humidity_last_entry = file[95,2]
humidity_last_entry

75.8

In [ ]:
# get 2nd and 3rd column
second_third_columns = file[:,2:4]
second_third_columns

In [29]:
# get the first 5 rows
first_five_rows = file[0:5,:]
first_five_rows

array([[ 0. ,  1. , 60. , 10. ,  0. , 20. ],
       [ 0. ,  1. , 60. , 15. ,  0. , 20. ],
       [ 0. ,  1. , 60. , 20. ,  0. , 20. ],
       [ 0. ,  1. , 65.8, 10. ,  0. , 20. ],
       [ 0. ,  1. , 65.8, 15. ,  0. , 20. ]])

### Calculations

In [31]:
# total number of deaths
total_number_deaths = file[:,4].sum()
total_number_deaths

275.0

In [84]:
# total number of snails that survived
# survived = initial - death
survived = file[:,5] - file[:,4]
survived

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       19., 19., 20., 19., 20., 20., 20., 20., 20., 20., 20., 19., 16.,
       15., 20., 18., 16., 20., 18., 17., 20., 19., 18., 13., 13., 13.,
       16., 16., 13., 17., 17., 15., 18., 17., 17., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20., 20., 20., 17., 18., 20., 18.,
       19., 20., 20., 19., 19., 20., 19., 13.,  9.,  9., 16., 15., 11.,
       18., 16., 14., 18., 17., 15.,  8.,  6.,  4., 10.,  8.,  8., 15.,
       13., 11., 16., 15., 13.])

In [37]:
# total nuber that survived
print(f"The total number of snails that survived are {np.sum(survived)}")

The total number of snails that survived are 1645.0


In [38]:
# maximum temperature (column 3)
print(f"The maximum temperature is {file[:,3].max()}")

The maximum temperature is 20.0


In [39]:
# mean humidity
print(f"The mean humidity is {file[:,2].mean()}")

The mean humidity is 68.02499999999999


In [42]:
# average death rate = total death / total time
print(f"The average death rate per week is {(file[:,4].sum())/4}")

The average death rate per week is 68.75


In [75]:
#file[file[:,0]==0]

In [77]:
# Split the snails in 2 arrays based on their species
species0 = file[file[:,0] == 0]
species1 = file[file[:,0] == 1]
#species0, species1

In [79]:
# Which group of snails has the highest average death rate?
species0_death_rate = species0[:,4].sum()/4
species1_death_rate = species1[:,4].sum()/4
print(f"The death rate for species 0 is {species0_death_rate} and {species1_death_rate} for species 1")

The death rate for species 0 is 20.5 and 48.25 for species 1


Thus, Species 1 has the highest death rate per week

In [98]:
# What are the optimum living conditions (temperature and humidity) for snails?
# Use only snails kept for the full duration of the experiment.
least_death = file[file[:,1] == 4]