# Wk2 Trk1, Day 1, Part 1: 06/09/21
<br>

# Exercises: NumPy
---
<br>


Welcome to the first half of today's lab! In this lab, we are going to practice the fundamentals of numpy by creating arrays, accessing elements, subsetting using Boolean indexing and finally, we are also going to practice some well known numpy functions. 


Of course, we are not able to cover it all and as such we recommend the online resouces below. As always, documentation is your friend, so make sure you have a look if uncertain. 

Useful references: 
* [Official NumPy reference ](https://numpy.org/doc/stable/reference/index.html)
* [Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)


In [1]:
#first step if we want to use functions that have been already implemented in a library is to import that library

#traditional way of importing numpy
import numpy as np

#### Task 1: Mastering the basics

##### Part A: Create some arrays


* Create an array from the following list 
        sample_list = [1.0,4.0,9.0,23.0]

* **Do not use** *np.array* for the next problems: 
    * create a 10 x 10 matrix of all ones
    * a 15 element vector, with all elements equal to np.pi
    * an 1D array with elements between 0 and 50, stepping by 2
    * an array of random numbers of 0 mean and unit std; choose the size yourselves 
    * create an array of even numbers between 100 and 500 and then divide it by 2





In [2]:
#YOUR CODE GOES HERE

#those should be relatively easy if they attended the lecture. 
#Do not help too much here and encourage them to look at the documentation

In [3]:
sample_array = np.array([1.0,4.0,9.0,23.0])

ten_by_ten = np.ones((10,10))

pi_el = np.full(15,np.pi)

arr_to50 = np.arange(50,step=2)

r = np.random.normal(0, 1, (40,))

even = np.arange(100,500,2)
res = even/2

##### Part B: Practing indexing and slicing

Given the array below, access the following elements:

* access 39 using negative indexing
* slice the first five elements of each row
* slice the numbers between 0 and 5
* slice all the odd numbers (use Boolean indexing)

In [4]:
test1 = np.arange(0,40).reshape(2,20)

In [5]:
## YOUR CODE GOES HERE

print (test1)
print ("----------")
print (test1[1,-1])
print ("----------")
print (test1[:,:5])
print ("----------")
print (test1[test1<5])
print ("----------")
print (test1[test1%2!=0])


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]
----------
39
----------
[[ 0  1  2  3  4]
 [20 21 22 23 24]]
----------
[0 1 2 3 4]
----------
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


#### Task 2: Snails

The snails data can be found in the dataLab folder. 

Groups of 20 snails were held for periods of 1, 2, 3 or 4 weeks in carefully controlled conditions of temperature
and relative humidity. The two species of snails are labelled as 0 and 1. At the end of the exposure time the snails were tested to see if
they had survived.

Data format, 6 columns as follows: 
    * species (0 or 1)
    * exposure (weeks)
    * humidity
    * temperature
    * ndeaths
    * nsnails (initial number at the start)
    
    
    
**What you need to do**: 

* Read the data. Use numpy!
* Practice indexing and slicing: 
        * temperature of last entry
        * humidity of the 5th entry
        * get 2nd and 3rd column
        * get the first 5 rows
        
* Compute the following: 
        * total number of deaths :(
        * total number of snails that survived :)
        * max temperature
        * mean humidity
        * average death rate 
* Split the snails in 2 arrays based on their species
* Which group of snails has the highest average death rate? 
* What are the optimum living conditions (temperature and humidity) for snails? Use only snails kept for the full duration of the experiment. 


In [10]:
snails = np.loadtxt("labData/snails.txt")

In [50]:
temp_last = snails[-1,3]
hum_5th = snails[4,2]
cols_2_3 = snails[:,1:3]
first_5 = snails[:5,:]

[[ 0.   1.  60.  10.   0.  20. ]
 [ 0.   1.  60.  15.   0.  20. ]
 [ 0.   1.  60.  20.   0.  20. ]
 [ 0.   1.  65.8 10.   0.  20. ]
 [ 0.   1.  65.8 15.   0.  20. ]]


In [53]:
total_deaths = np.sum(snails[:,4])
alive = np.sum(snails[:,5]) - total_deaths
max_temp = np.max(snails[:,3])
mean_hum = np.mean(snails[:,2])
average_death_rate = np.mean(snails[:,4]/ snails[:,5])

In [54]:
species_0 = snails[snails[:,0]==0]
species_1 = snails[snails[:,0]==1]

In [55]:
average_death_rate_0 = np.mean(species_0[:,4]/ species_0[:,5])
average_death_rate_1 = np.mean(species_1[:,4]/ species_1[:,5])

weakest_snail = 0 if average_death_rate_0>average_death_rate_1 else 1
print("weakest_snail\n",weakest_snail)

weakest_snail
 1


In [58]:
#optimum living condition 
deaths = snails[:,4]/ snails[:,5]
death_rate = np.sort(deaths)

death_rate_order = np.argsort(deaths)
exposure_death_order = snails[:,1][death_rate_order]

week_4 = snails[snails[:,1]==4]
week_4_deaths = week_4[:,4]/ week_4[:,5]

best_conditions = np.argmin(week_4_deaths)